language: node_js
node_js:
  - "12.0.0"
sudo: required
services:
  - docker

before_install:
  - docker build -t kanishkaw/docker-react -f Dockerfile.dev .

script:
  - docker run kanishkaw/docker-react npm run test -- --coverage --watchAll=false