language: node_js
node_js:
  - "12.0.0"
sudo: required
services:
  - docker

before_install:
  - docker build -t kanishkaw/docker-react -f Dockerfile.dev .

script:
  - docker run kanishkaw/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-245710842330"
  bucket_path: "docker-react"
  zip_file: "app.zip"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY